'use client';

import {
  CalcRulesConfig,
  CalculatorDraft,
  PriceBook,
  SidingTypeRow,
  TopOfSidingMode,
  WORK_SECTIONS,
} from '@/lib/types';
import { BRANDS, Brand, STYLES, Style, brandSupportsPrimed } from '@/lib/brands';
import { MAX_SIDING_ROWS } from '@/lib/calc/sidingRows';
import { effectiveMeasurements } from '@/lib/calc/measurements';
import { computeCalculation } from '@/lib/calc/engine';
import { LineItemPickList } from '@/components/LineItemPickList';
import { MaterialLaborList } from '@/components/MaterialLaborList';
import { NextButton } from '@/components/NextButton';

interface Props {
  draft: CalculatorDraft;
  updateDraft: (updater: (d: CalculatorDraft) => CalculatorDraft) => void;
  priceBook: PriceBook;
  calcRules: CalcRulesConfig;
  onNext: () => void;
}

function findSidingProduct(priceBook: PriceBook, brand: Brand, style: Style, primed: boolean) {
  return priceBook.items.find(
    (i) => i.category === 'siding' && i.brand === brand && i.style === style && i.primed === primed
  );
}

export function QuoteDetailsTab({ draft, updateDraft, priceBook, calcRules, onNext }: Props) {
  const qd = draft.quoteDetails;
  const tc = draft.trimConfig;
  const em = effectiveMeasurements(draft.measurements);
  const accessoryItems = priceBook.items.filter((i) => i.category === 'siding-accessory' && i.active);
  const result = computeCalculation(draft, priceBook, calcRules);

  const areaSum = draft.sidingTypeRows.reduce((s, r) => s + (r.areaSqft || 0), 0);
  const areaMismatch = Math.abs(areaSum - em.facadeAreaSqft) > 0.5;

  function updateRow(id: string, patch: Partial<SidingTypeRow>) {
    updateDraft((d) => ({
      ...d,
      sidingTypeRows: d.sidingTypeRows.map((r) => {
        if (r.id !== id) return r;
        const merged = { ...r, ...patch };
        if ('brand' in patch || 'style' in patch || 'primed' in patch) {
          const product = findSidingProduct(priceBook, merged.brand, merged.style, merged.primed);
          merged.productId = product?.id ?? null;
        }
        return merged;
      }),
    }));
  }

  function addRow() {
    updateDraft((d) => {
      if (d.sidingTypeRows.length >= MAX_SIDING_ROWS) return d;
      const brand: Brand = 'Vinyl';
      const style: Style = 'Lap';
      const product = findSidingProduct(priceBook, brand, style, false);
      return {
        ...d,
        sidingTypeRows: [
          ...d.sidingTypeRows,
          { id: crypto.randomUUID(), brand, style, primed: false, productId: product?.id ?? null, areaSqft: 0, autoGenerated: false },
        ],
      };
    });
  }

  function removeRow(id: string) {
    updateDraft((d) => ({ ...d, sidingTypeRows: d.sidingTypeRows.filter((r) => r.id !== id) }));
  }

  function setTrimField<K extends keyof typeof tc>(key: K, value: (typeof tc)[K]['value']) {
    updateDraft((d) => ({
      ...d,
      trimConfig: { ...d.trimConfig, [key]: { value, overridden: true } },
    }));
  }

  return (
    <div className="space-y-6">
      <div className="card overflow-x-auto">
        <div className="mb-3 flex items-center justify-between">
          <h2 className="text-lg font-bold">Siding Types</h2>
          <button className="btn btn-secondary btn-sm" onClick={addRow} disabled={draft.sidingTypeRows.length >= MAX_SIDING_ROWS}>
            + Add Row
          </button>
        </div>
        <table className="data-table">
          <thead>
            <tr>
              <th>Brand</th>
              <th>Style</th>
              <th>Primed</th>
              <th className="text-right">Area (sqft)</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {draft.sidingTypeRows.map((row) => (
              <tr key={row.id}>
                <td>
                  <select className="field-input" value={row.brand} onChange={(e) => updateRow(row.id, { brand: e.target.value as Brand })}>
                    {BRANDS.map((b) => (
                      <option key={b} value={b}>
                        {b}
                      </option>
                    ))}
                  </select>
                </td>
                <td>
                  <select className="field-input" value={row.style} onChange={(e) => updateRow(row.id, { style: e.target.value as Style })}>
                    {STYLES.map((s) => (
                      <option key={s} value={s}>
                        {s}
                      </option>
                    ))}
                  </select>
                </td>
                <td>
                  <select
                    className="field-input"
                    value={row.primed ? 'primed' : 'unprimed'}
                    disabled={!brandSupportsPrimed(row.brand)}
                    onChange={(e) => updateRow(row.id, { primed: e.target.value === 'primed' })}
                  >
                    <option value="unprimed">Unprimed</option>
                    <option value="primed">Primed</option>
                  </select>
                </td>
                <td>
                  <input
                    type="number"
                    step="any"
                    className="field-input text-right"
                    value={row.areaSqft}
                    onChange={(e) => updateRow(row.id, { areaSqft: parseFloat(e.target.value) || 0 })}
                  />
                </td>
                <td>
                  <button className="btn btn-danger btn-sm" onClick={() => removeRow(row.id)}>
                    Remove
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
          <tfoot>
            <tr>
              <td colSpan={3}>Sum vs. Facade Area ({em.facadeAreaSqft.toFixed(1)} sqft)</td>
              <td className="text-right">{areaSum.toFixed(1)}</td>
              <td></td>
            </tr>
          </tfoot>
        </table>
        {areaMismatch && (
          <p className="mt-2 text-sm font-semibold text-amber-600">
            ⚠ Siding row areas ({areaSum.toFixed(1)} sqft) don&rsquo;t match the facade total ({em.facadeAreaSqft.toFixed(1)} sqft).
          </p>
        )}
      </div>

      <div className="card">
        <h2 className="mb-3 text-lg font-bold">Siding Accessories</h2>
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <div>
            <label className="field-label">Trim Around Openings</label>
            <select className="field-input" value={tc.openingsTrimProductId.value ?? ''} onChange={(e) => setTrimField('openingsTrimProductId', e.target.value || null)}>
              <option value="">None</option>
              {accessoryItems.map((i) => (
                <option key={i.id} value={i.id}>
                  {i.name}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="field-label">Outside Corner Posts</label>
            <select className="field-input" value={tc.outsideCornerProductId.value ?? ''} onChange={(e) => setTrimField('outsideCornerProductId', e.target.value || null)}>
              <option value="">None</option>
              {accessoryItems.map((i) => (
                <option key={i.id} value={i.id}>
                  {i.name}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="field-label">Inside Corner Posts</label>
            <select className="field-input" value={tc.insideCornerProductId.value ?? ''} onChange={(e) => setTrimField('insideCornerProductId', e.target.value || null)}>
              <option value="">None</option>
              {accessoryItems.map((i) => (
                <option key={i.id} value={i.id}>
                  {i.name}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="field-label">Starter</label>
            <select className="field-input" value={tc.starterProductId.value ?? ''} onChange={(e) => setTrimField('starterProductId', e.target.value || null)}>
              <option value="">None</option>
              {accessoryItems.map((i) => (
                <option key={i.id} value={i.id}>
                  {i.name}
                </option>
              ))}
            </select>
          </div>
        </div>

        <div className="mt-4">
          <label className="field-label">Top-of-Siding Trim</label>
          <div className="flex gap-2">
            {(['eaves-only', 'eaves-gables'] as TopOfSidingMode[]).map((mode) => (
              <button
                key={mode}
                className="pill"
                data-active={tc.topOfSidingMode.value === mode ? 'true' : 'false'}
                onClick={() => setTrimField('topOfSidingMode', mode)}
              >
                {mode === 'eaves-only' ? 'Eaves Only' : 'Eaves + Gables'}
              </button>
            ))}
          </div>
        </div>

        <div className="mt-4 flex flex-wrap gap-2">
          <button className="pill" data-active={tc.buttJointFlashing.value ? 'true' : 'false'} onClick={() => setTrimField('buttJointFlashing', !tc.buttJointFlashing.value)}>
            {tc.buttJointFlashing.value ? '☑' : '☐'} Butt Joint Flashing
          </button>
          <button className="pill" data-active={tc.touchUpPaint.value ? 'true' : 'false'} onClick={() => setTrimField('touchUpPaint', !tc.touchUpPaint.value)}>
            {tc.touchUpPaint.value ? '☑' : '☐'} Touch-Up Paint
          </button>
          <button className="pill" data-active={tc.caulkSealant.value ? 'true' : 'false'} onClick={() => setTrimField('caulkSealant', !tc.caulkSealant.value)}>
            {tc.caulkSealant.value ? '☑' : '☐'} Caulk / Sealant
          </button>
        </div>
      </div>

      {draft.workSections.sheathing && (
        <div className="card">
          <h2 className="mb-3 text-lg font-bold">{WORK_SECTIONS.find((s) => s.key === 'sheathing')?.label}</h2>
          <LineItemPickList
            category="sheathing"
            picks={qd.sheathing}
            priceBook={priceBook}
            defaultQty={em.facadeAreaSqft}
            onChange={(picks) => updateDraft((d) => ({ ...d, quoteDetails: { ...d.quoteDetails, sheathing: picks } }))}
          />
        </div>
      )}

      {draft.workSections.demoRemoval && (
        <div className="card">
          <h2 className="mb-3 text-lg font-bold">Demo &amp; Removal</h2>
          <LineItemPickList
            category="demo-removal"
            picks={qd.demolitionMaterials}
            priceBook={priceBook}
            defaultQty={em.facadeAreaSqft}
            onChange={(picks) => updateDraft((d) => ({ ...d, quoteDetails: { ...d.quoteDetails, demolitionMaterials: picks } }))}
          />
        </div>
      )}

      {draft.workSections.fixtures && (
        <div className="card">
          <h2 className="mb-3 text-lg font-bold">Fixtures</h2>
          <LineItemPickList
            category="fixtures"
            picks={qd.fixtures}
            priceBook={priceBook}
            defaultQty={1}
            onChange={(picks) => updateDraft((d) => ({ ...d, quoteDetails: { ...d.quoteDetails, fixtures: picks } }))}
          />
        </div>
      )}

      {draft.workSections.furringFraming && (
        <div className="card">
          <h2 className="mb-3 text-lg font-bold">Furring &amp; Framing</h2>
          <LineItemPickList
            category="furring-framing"
            picks={qd.furringFraming}
            priceBook={priceBook}
            defaultQty={0}
            onChange={(picks) => updateDraft((d) => ({ ...d, quoteDetails: { ...d.quoteDetails, furringFraming: picks } }))}
          />
        </div>
      )}

      {draft.workSections.aluminumWraps && (
        <div className="card">
          <h2 className="mb-3 text-lg font-bold">Aluminum Wraps</h2>
          <LineItemPickList
            category="aluminum-wraps"
            picks={qd.aluminumWraps}
            priceBook={priceBook}
            defaultQty={1}
            onChange={(picks) => updateDraft((d) => ({ ...d, quoteDetails: { ...d.quoteDetails, aluminumWraps: picks } }))}
          />
        </div>
      )}

      {draft.workSections.doorWindowInstalls && (
        <div className="card">
          <h2 className="mb-3 text-lg font-bold">Door &amp; Window Installs</h2>
          <LineItemPickList
            category="door-window-installs"
            picks={qd.doorWindowInstalls}
            priceBook={priceBook}
            defaultQty={1}
            onChange={(picks) => updateDraft((d) => ({ ...d, quoteDetails: { ...d.quoteDetails, doorWindowInstalls: picks } }))}
          />
        </div>
      )}

      {draft.workSections.paintingCoating && (
        <div className="card">
          <h2 className="mb-3 text-lg font-bold">Painting / Coating</h2>
          <LineItemPickList
            category="painting-coating"
            picks={qd.paintingCoating}
            priceBook={priceBook}
            defaultQty={em.facadeAreaSqft}
            onChange={(picks) => updateDraft((d) => ({ ...d, quoteDetails: { ...d.quoteDetails, paintingCoating: picks } }))}
          />
        </div>
      )}

      {draft.workSections.soffit && (
        <div className="card">
          <h2 className="mb-1 text-lg font-bold">Soffit</h2>
          <p className="mb-3 text-xs text-gray-500">Material and removal choice set in Checklist. Computed below.</p>
          {result.sections.find((s) => s.section === 'soffit') && (
            <MaterialLaborList result={{ sections: [result.sections.find((s) => s.section === 'soffit')!], materialTotal: 0, laborTotal: 0, grandTotal: 0 }} />
          )}
        </div>
      )}

      {draft.workSections.fascia && (
        <div className="card">
          <h2 className="mb-1 text-lg font-bold">Fascia</h2>
          <p className="mb-3 text-xs text-gray-500">Material and removal choice set in Checklist. Computed below.</p>
          {result.sections.find((s) => s.section === 'fascia') && (
            <MaterialLaborList result={{ sections: [result.sections.find((s) => s.section === 'fascia')!], materialTotal: 0, laborTotal: 0, grandTotal: 0 }} />
          )}
        </div>
      )}

      {draft.workSections.gutters && (
        <div className="card">
          <h2 className="mb-1 text-lg font-bold">Gutters</h2>
          <p className="mb-3 text-xs text-gray-500">Size, downspouts, guards, and removal choice set in Checklist. Computed below.</p>
          {result.sections.find((s) => s.section === 'gutters') && (
            <MaterialLaborList result={{ sections: [result.sections.find((s) => s.section === 'gutters')!], materialTotal: 0, laborTotal: 0, grandTotal: 0 }} />
          )}
        </div>
      )}

      {draft.workSections.oneTimeCharges && (
        <div className="card">
          <h2 className="mb-3 text-lg font-bold">One-Time Charges</h2>
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
            {(
              [
                ['threeStory', '3-Story Charge', 'toggle'],
                ['tripCharge', 'Trip Charge', 'toggle'],
                ['laborMinimum', 'Labor Minimum', 'toggle'],
                ['portableToilet', 'Portable Toilet Rental', 'toggle'],
                ['dumpsterWasteDisposal', 'Dumpster / Waste Disposal', 'toggle'],
                ['materialDeliveryFee', 'Material Delivery Fee', 'toggle'],
                ['permitFee', 'Permit Fee', 'toggle'],
                ['scaffoldingLiftRental', 'Scaffolding / Lift Rental', 'toggle'],
              ] as const
            ).map(([key, label]) => (
              <button
                key={key}
                className="pill"
                data-active={qd.oneTimeCharges[key] ? 'true' : 'false'}
                onClick={() =>
                  updateDraft((d) => ({
                    ...d,
                    quoteDetails: { ...d.quoteDetails, oneTimeCharges: { ...d.quoteDetails.oneTimeCharges, [key]: !d.quoteDetails.oneTimeCharges[key] } },
                  }))
                }
              >
                {qd.oneTimeCharges[key] ? '☑' : '☐'} {label}
              </button>
            ))}
          </div>
          <div className="mt-3 grid grid-cols-2 gap-4 sm:grid-cols-3">
            <div>
              <label className="field-label">OSB / Insulation Board (sqft)</label>
              <input
                type="number"
                className="field-input"
                value={qd.oneTimeCharges.osbInsulationBoardSqft}
                onChange={(e) =>
                  updateDraft((d) => ({
                    ...d,
                    quoteDetails: { ...d.quoteDetails, oneTimeCharges: { ...d.quoteDetails.oneTimeCharges, osbInsulationBoardSqft: parseFloat(e.target.value) || 0 } },
                  }))
                }
              />
            </div>
            <div>
              <label className="field-label">Detach &amp; Reset Lights (qty)</label>
              <input
                type="number"
                className="field-input"
                value={qd.oneTimeCharges.detachResetLightQty}
                onChange={(e) =>
                  updateDraft((d) => ({
                    ...d,
                    quoteDetails: { ...d.quoteDetails, oneTimeCharges: { ...d.quoteDetails.oneTimeCharges, detachResetLightQty: parseFloat(e.target.value) || 0 } },
                  }))
                }
              />
            </div>
          </div>
        </div>
      )}

      <div className="card">
        <h2 className="mb-3 text-lg font-bold">Material and Labor List</h2>
        <MaterialLaborList result={result} exportFileName="material-and-labor-list.csv" />
      </div>

      <NextButton onClick={onNext} label="Next: Proposal" />
    </div>
  );
}
