import { Brand, Style } from '../brands';
import { PriceBook, SidingMaterialSelections, SidingTypeRow, sidingKey } from '../types';
import { trimConfigForBrand } from './trimSwitch';

export const MAX_SIDING_ROWS = 4;

/** Keeps auto-generated Siding Type rows in sync with the checked material×style combos, capped at 4. */
export function syncSidingRowsFromSelections(
  rows: SidingTypeRow[],
  selections: SidingMaterialSelections,
  priceBook: PriceBook
): SidingTypeRow[] {
  const checkedKeys = Object.entries(selections)
    .filter(([, checked]) => checked)
    .map(([key]) => key);

  let next = rows.filter((r) => !r.autoGenerated || checkedKeys.includes(sidingKey(r.brand, r.style)));

  for (const key of checkedKeys) {
    const [brand, style] = key.split('|') as [Brand, Style];
    const exists = next.some((r) => r.brand === brand && r.style === style);
    if (!exists && next.length < MAX_SIDING_ROWS) {
      const product = priceBook.items.find(
        (i) => i.category === 'siding' && i.brand === brand && i.style === style && i.primed === false
      );
      next = [
        ...next,
        {
          id: crypto.randomUUID(),
          brand,
          style,
          primed: false,
          productId: product?.id ?? null,
          areaSqft: 0,
          sectionIds: [],
          autoGenerated: true,
          trimConfig: trimConfigForBrand(brand),
        },
      ];
    }
  }

  return next;
}
